### ISSUE TITLE
Problems on Snow Leopard

### ISSUE THREAD

**Issue by dza2000** [dima/restfulx_framework#35]
I am working on a MBP with OS X 10.6.  I have followed the tutorial, and when I ran rake fx:flex:build, I get an error inside of my Aptana console that says this:

The application was not compiled. Check console for errors. It is possible that '(a)mxmlc' executable was not found or there are compilation errors.

I tried to use the mxml compiler in Terminal and got the following error:

/Users/donanddeesullivan/Documents/AptanaStudioWorkspace/pomodo/app/flex/pomodo/controllers/ApplicationController.as(10): col: 46 Error: The definition of base class RxApplicationController was not found.

  public class ApplicationController extends RxApplicationController {
                                             ^
What gives?  I would LOVE to use this gem for some things I am doing at work, but I can't get it to work for me.

**Comment by dima** [comment]
Looks like you are missing restfulx.swc file from your lib folder. You might have forgotten to run ./script/generate rx_config to fetch the binary of the framework. You can also download it directly from restfulx.github.com by clicking on the 1.2.4 red label.

**Comment by dza2000** [comment]
Dima,

I checked my folders, and restfulx.swc is inside my lib folder.  Not sure why I am getting this error.

**Comment by dima** [comment]
Definitely not a general issue (plenty of people using Snow Leopard and have no issues).
